version: '3'

services:  
  postgres:
    container_name: spike_postgres
    image: "postgres:12.0"
    env_file:
      - .env
    ports:
      - 4321:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data