training: {
    model: 'dcgan',
    symbol: 'eurusd_m1',
    spread: 0.0003,
    start_date: '2008-01-01',
    sequence_len: 512, 
    batch_size: 64,
    noise_dim: 128,
    num_epochs: 300,
    optimizer: {
        name: 'adam',
        learning_rate: 0.0001
    },
    tensorboard_path: '/home/joel/AISG/UDP/spike/spike/tb_logs'
}

checkpoint: {
    model: 'dcgan',
    max_to_keep: 10,
    ckpt_step: 5,
    ckpt_path: '/home/joel/AISG/UDP/spike/spike/tf_ckpts',
}