training: {
    model: 'dcgan',
    symbol: 'eurusd_m1',
    spread: 0.0003,
    start_date: '2018-01-01',
    seq_len: 512, 
    batch_size: 128,
    input_dim: 4,
    noise_dim: 64,
    num_epochs: 501,
    optimizer: {
        name: 'adam',
        learning_rate: 0.0002
    },
    tensorboard_path: '/home/joel/AISG/UDP/spike/spike/tb_logs',
    random_seed: 8765,
    restore_ckpt: False,
}

checkpoint: {
    model: 'dcgan',
    max_to_keep: 10,
    ckpt_step: 100,
    ckpt_path: '/home/joel/AISG/UDP/spike/spike/tf_ckpts',
    gen_step: 25,
}