training: {
    model_name: 'dcgan',
    model: 'dcgan',
    symbol: 'eurusd_m1',
    spread: 0.0003,
    start_date: '2010-01-01',
    sequence_len: 512, 
    batch_size: 64,
    noise_dim: 128,
    num_epochs: 1000,
    optimizer: {
        name: 'adam',
        learning_rate: 0.0001
    },
    tensorboard_path: '/home/joel/AISG/UDP/spike/spike'
}

checkpoint: {
    model: 'dcgan',
    ckpt_manager: '',
    ckpt_path: '/home/joel/AISG/UDP/spike/spike',
    epoch_path: '',
    last_epoch: '',
}